wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1685597660
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 13
      - 16
      - 19
      4: 3.9.13
      5: 0.12.17
      8:
      - 3
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 8
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
cfg:
  desc: null
  value: cfg/training/yolov7.yaml
data:
  desc: null
  value: data/mydata.yaml
data_dict:
  desc: null
  value:
    names:
    - 3+2-2
    - 3-2-2
    - 3jia2
    - aerbeisi
    - anmuxi
    - aoliao
    - asamu
    - baicha
    - baishikele
    - baishikele-2
    - baokuangli
    - binghongcha
    - bingqilinniunai
    - bingtangxueli
    - buding
    - chacui
    - chapai
    - chapai2
    - damaicha
    - daofandian1
    - daofandian2
    - daofandian3
    - daofandian4
    - dongpeng
    - dongpeng-b
    - fenda
    - gudasao
    - guolicheng
    - guolicheng2
    - haitai
    - haochidian
    - haoliyou
    - heweidao
    - heweidao2
    - heweidao3
    - hongniu
    - hongniu2
    - hongshaoniurou
    - jianjiao
    - jianlibao
    - jindian
    - kafei
    - kaomo_gali
    - kaomo_jiaoyan
    - kaomo_shaokao
    - kaomo_xiangcon
    - kebike
    - kele
    - kele-b
    - kele-b-2
    - laotansuancai
    - liaomian
    - libaojian
    - lingdukele
    - lingdukele-b
    - liziyuan
    - lujiaoxiang
    - lujikafei
    - luxiangniurou
    - maidong
    - mangguoxiaolao
    - meiniye
    - mengniu
    - mengniuzaocan
    - moliqingcha
    - nfc
    - niudufen
    - niunai
    - nongfushanquan
    - qingdaowangzi-1
    - qingdaowangzi-2
    - qinningshui
    - quchenshixiangcao
    - rancha-1
    - rancha-2
    - rousongbing
    - rusuanjunqishui
    - suanlafen
    - suanlaniurou
    - taipingshuda
    - tangdaren
    - tangdaren2
    - tangdaren3
    - ufo
    - ufo2
    - wanglaoji
    - wanglaoji-c
    - wangzainiunai
    - weic
    - weitanai
    - weitanai2
    - weitanaiditang
    - weitaningmeng
    - weitaningmeng-bottle
    - weiweidounai
    - wuhounaicha
    - wulongcha
    - xianglaniurou
    - xianguolao
    - xianxiayuban
    - xuebi
    - xuebi-b
    - xuebi2
    - yezhi
    - yibao
    - yida
    - yingyangkuaixian
    - yitengyuan
    - youlemei
    - yousuanru
    - youyanggudong
    - yuanqishui
    - zaocanmofang
    - zihaiguo
    nc: 114
    test: data/test/images
    train: data/train/images
    val: data/valid/images
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 100
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.3
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    loss_ota: 1
    lr0: 0.01
    lrf: 0.1
    mixup: 0.15
    momentum: 0.937
    mosaic: 1.0
    obj: 0.7
    obj_pw: 1.0
    paste_in: 0.15
    perspective: 0.0
    scale: 0.9
    shear: 0.0
    translate: 0.2
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 640
  - 640
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
opt:
  desc: null
  value:
    adam: false
    artifact_alias: latest
    batch_size: 8
    bbox_interval: -1
    bucket: ''
    cache_images: false
    cfg: cfg/training/yolov7.yaml
    data: data/mydata.yaml
    device: ''
    entity: null
    epochs: 100
    evolve: false
    exist_ok: false
    freeze:
    - 0
    global_rank: -1
    hyp:
      anchor_t: 4.0
      box: 0.05
      cls: 0.3
      cls_pw: 1.0
      copy_paste: 0.0
      degrees: 0.0
      fl_gamma: 0.0
      fliplr: 0.5
      flipud: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      iou_t: 0.2
      loss_ota: 1
      lr0: 0.01
      lrf: 0.1
      mixup: 0.15
      momentum: 0.937
      mosaic: 1.0
      obj: 0.7
      obj_pw: 1.0
      paste_in: 0.15
      perspective: 0.0
      scale: 0.9
      shear: 0.0
      translate: 0.2
      warmup_bias_lr: 0.1
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      weight_decay: 0.0005
    image_weights: false
    img_size:
    - 640
    - 640
    label_smoothing: 0.0
    linear_lr: false
    local_rank: -1
    multi_scale: false
    name: exp
    noautoanchor: false
    nosave: false
    notest: false
    project: runs/train
    quad: false
    rect: false
    resume: false
    save_dir: runs\train\exp
    save_period: -1
    single_cls: false
    sync_bn: false
    total_batch_size: 8
    upload_dataset: false
    v5_metric: false
    weights: yolov7.pt
    workers: 8
    world_size: 1
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs\train\exp
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 8
upload_dataset:
  desc: null
  value: false
v5_metric:
  desc: null
  value: false
weights:
  desc: null
  value: yolov7.pt
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
